"use client";
import { useRef, useState } from "react";
import { ArrowRight, Check, LockKeyhole, LoaderCircle } from "lucide-react";
import { Checkbox } from "@/components/ui/checkbox";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
export function Choice({label,value,onChange,options,id}:{label:string;value:string;onChange:(v:string)=>void;options:[string,string][];id:string}){return <div className="field"><label id={id+"-label"}>{label}</label><Select value={value} onValueChange={onChange}><SelectTrigger aria-labelledby={id+"-label"} id={id}><SelectValue/></SelectTrigger><SelectContent>{options.map(([v,l])=><SelectItem value={v} key={v}>{l}</SelectItem>)}</SelectContent></Select></div>}
export default function LeadForm(){
 const [modality,setModality]=useState("orientacion"),[budget,setBudget]=useState("por-definir"),[timeline,setTimeline]=useState("explorando"),[intent,setIntent]=useState("informacion");
 const [consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[reference,setReference]=useState("");const id=useRef("");
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError("");if(!consent){setError("Acepta el uso de tus datos para que podamos atender tu consulta.");return;}setBusy(true);const data=new FormData(e.currentTarget);if(!id.current)id.current=crypto.randomUUID();
 try{const params=new URLSearchParams(location.search);const source=[params.get("utm_source"),params.get("utm_medium"),params.get("utm_campaign")].filter(Boolean).join(" / ").slice(0,200)||"directo";
 const r=await fetch("/api/leads",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...Object.fromEntries(data),id:id.current,modality,budget,timeline,intent,consent,source})});const result=await r.json() as {error?:string;reference:string};if(!r.ok)throw new Error(result.error||"No se pudo guardar la consulta.");setReference(result.reference);
 }catch(e){setError(e instanceof Error?e.message:"No pudimos conectar. Inténtalo de nuevo.");}finally{setBusy(false);}}
 if(reference)return <div className="form-success" role="status"><span className="success-icon"><Check/></span><div className="eyebrow">SOLICITUD REGISTRADA</div><h3>Tu siguiente paso<br/>ya está en marcha.</h3><p>Hemos guardado tu interés en El Bindho. Conserva tu referencia para dar seguimiento.</p><strong className="reference">{reference}</strong><p className="small-copy">La recepción no confirma una cita, reserva del terreno ni acceso al expediente. El equipo revisará tu solicitud antes de avanzar.</p><a className="button outline" href="/ficha">Ver ficha del activo <ArrowRight size={17}/></a></div>;
 return <form className="lead-form" onSubmit={submit}><div className="form-heading"><h3>Hablemos de tu proyecto.</h3><p>Cuéntanos qué buscas. Los campos con * son obligatorios.</p></div><div className="form-grid">
 <div className="field"><label htmlFor="name">Nombre completo *</label><input id="name" name="name" autoComplete="name" required minLength={2} maxLength={120} placeholder="Tu nombre"/></div>
 <div className="field"><label htmlFor="email">Correo electrónico *</label><input id="email" name="email" type="email" autoComplete="email" required maxLength={200} placeholder="nombre@empresa.com"/></div>
 <div className="field"><label htmlFor="phone">Teléfono / WhatsApp</label><input id="phone" name="phone" type="tel" autoComplete="tel" maxLength={35} placeholder="+52"/></div>
 <div className="field"><label htmlFor="company">Empresa</label><input id="company" name="company" autoComplete="organization" maxLength={160} placeholder="Empresa o fondo"/></div>
 <Choice id="modality" label="Modalidad de interés" value={modality} onChange={setModality} options={[["orientacion","Quiero orientación"],["A","Compra directa"],["B","Aportación a fideicomiso"],["C","Coinversión"]]}/>
 <Choice id="intent" label="¿Cómo quieres avanzar?" value={intent} onChange={setIntent} options={[["informacion","Recibir información"],["visita","Solicitar una visita"],["documentacion","Solicitar documentación"],["propuesta","Presentar una propuesta"]]}/>
 <Choice id="budget" label="Capital previsto (MXN)" value={budget} onChange={setBudget} options={[["por-definir","Por definir"],["menos-10","Menos de $10 millones"],["10-30","$10 a $30 millones"],["30-50","$30 a $50 millones"],["mas-50","Más de $50 millones"]]}/>
 <Choice id="timeline" label="Plazo de decisión" value={timeline} onChange={setTimeline} options={[["explorando","Estoy explorando"],["0-3","En los próximos 3 meses"],["3-6","Entre 3 y 6 meses"],["6-12","Entre 6 y 12 meses"]]}/>
 <div className="field full"><label htmlFor="message">Cuéntanos sobre tu proyecto</label><textarea id="message" name="message" maxLength={2000} rows={3} placeholder="Tipo de proyecto, dudas o disponibilidad para una visita…"/></div>
 </div><div className="honeypot" aria-hidden="true"><label>Dejar vacío<input name="website" tabIndex={-1} autoComplete="off"/></label></div>
 <div className="consent"><Checkbox id="consent" checked={consent} onCheckedChange={v=>setConsent(v===true)}/><label htmlFor="consent">Autorizo el uso de mis datos para atender esta solicitud conforme a la <a href="/privacidad" target="_blank" rel="noreferrer">información de privacidad</a>. *</label></div>
 {error&&<p className="form-error" role="alert">{error}</p>}<button className="button gold submit-button" disabled={busy} type="submit">{busy?<>Guardando solicitud <LoaderCircle className="spin" size={18}/></>:<>Enviar mi solicitud <ArrowRight size={18}/></>}</button><p className="form-footnote"><LockKeyhole size={13}/> No envíes escrituras, identificaciones ni comprobantes bancarios en este formulario.</p></form>;
}
