"use client";
import { useEffect, useRef, useState } from "react";
import { ArrowRight, Check, LockKeyhole, LoaderCircle, ChevronDown } from "lucide-react";
import { Checkbox } from "@/components/ui/checkbox";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
import { properties, type PropertyId } from "@/lib/properties";
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from "@/components/ui/collapsible";
export type LeadRequest={intent:string;modality:string;placement:string};
export function Choice({label,value,onChange,options,id}:{label:string;value:string;onChange:(v:string)=>void;options:[string,string][];id:string}){return <div className="field"><label id={id+"-label"}>{label}</label><Select value={value} onValueChange={onChange}><SelectTrigger aria-labelledby={id+"-label"} id={id}><SelectValue/></SelectTrigger><SelectContent>{options.map(([v,l])=><SelectItem value={v} key={v}>{l}</SelectItem>)}</SelectContent></Select></div>}
export default function LeadForm({request,propertyId="el-bindho"}:{request?:LeadRequest;propertyId?:PropertyId}){
 const property=properties[propertyId];const apartment=propertyId==="villas-de-la-hacienda";
 const [modality,setModality]=useState("orientacion"),[budget,setBudget]=useState("por-definir"),[timeline,setTimeline]=useState("explorando"),[intent,setIntent]=useState("informacion");
 const [consent,setConsent]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[reference,setReference]=useState(""),[details,setDetails]=useState(false);const id=useRef("");
 useEffect(()=>{if(request){setIntent(request.intent);setModality(request.modality);}},[request]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setError("");if(!consent){setError("Acepta el uso de tus datos para que podamos atender tu consulta.");return;}setBusy(true);const data=new FormData(e.currentTarget);if(!id.current)id.current=crypto.randomUUID();
 try{const params=new URLSearchParams(location.search);const campaign=[params.get("utm_source"),params.get("utm_medium"),params.get("utm_campaign")].filter(Boolean).join(" / ").slice(0,160)||"directo";const source=campaign+" | "+(request?.placement||"formulario");
 const r=await fetch("/api/leads",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({company:"",message:"",...Object.fromEntries(data),id:id.current,propertyId,modality,budget,timeline,intent,consent,source})});const result=await r.json() as {error?:string;reference:string};if(!r.ok)throw new Error(result.error||"No se pudo guardar la consulta.");setReference(result.reference);
 }catch(e){setError(e instanceof Error?e.message:"No pudimos conectar. Inténtalo de nuevo.");}finally{setBusy(false);}}
 if(reference)return <div id="solicitud" className="form-success" role="status"><span className="success-icon"><Check/></span><div className="eyebrow">SOLICITUD REGISTRADA</div><h3>Tu interés en {property.name}<br/>ha quedado registrado.</h3><p>El equipo podrá revisar tu consulta y contactarte por los datos que has facilitado. Conserva tu referencia.</p><strong className="reference">{reference}</strong><p className="small-copy">La recepción no confirma una cita, reserva del inmueble ni acceso al expediente.</p><a className="button outline" href={property.sheet}>Consultar ficha ahora <ArrowRight size={17}/></a></div>;
 return <form id="solicitud" className="lead-form" onSubmit={submit}><div className="form-heading"><h3>{intent==="visita"?`Solicita una visita a ${property.name}.`:`Solicita información de ${property.name}.`}</h3><p>Solo necesitamos tu nombre, correo y autorización para atenderte. Sin compromiso de compra.</p></div><div className="form-grid basic-fields">
 <div className="field"><label htmlFor="name">Nombre completo *</label><input id="name" name="name" autoComplete="name" required minLength={2} maxLength={120} placeholder="Tu nombre"/></div>
 <div className="field"><label htmlFor="email">Correo electrónico *</label><input id="email" name="email" type="email" autoComplete="email" required maxLength={200} placeholder="nombre@empresa.com"/></div>
 <div className="field"><label htmlFor="phone">Teléfono / WhatsApp (opcional)</label><input id="phone" name="phone" type="tel" autoComplete="tel" maxLength={35} placeholder="+52"/></div>
 <Choice id="intent" label="¿Cómo quieres avanzar?" value={intent} onChange={setIntent} options={[["informacion","Recibir información"],["visita","Solicitar una visita"],["documentacion","Solicitar documentación"],["propuesta","Presentar una propuesta"]]}/>
 </div><Collapsible open={details} onOpenChange={setDetails}><CollapsibleTrigger className="qualification-trigger" type="button">Añadir detalles de mi búsqueda (opcional)<ChevronDown size={17}/></CollapsibleTrigger><CollapsibleContent forceMount hidden={!details}><div className="form-grid qualification-fields">
 {!apartment&&<div className="field"><label htmlFor="company">Empresa (opcional)</label><input id="company" name="company" autoComplete="organization" maxLength={160} placeholder="Empresa o fondo"/></div>}
 <Choice id="modality" label={apartment?"Forma de compra (opcional)":"Modalidad de interés (opcional)"} value={modality} onChange={setModality} options={apartment?[["orientacion","Quiero orientación"],["contado","Recursos propios / contado"],["credito","Evaluar compra con crédito"]]:[["orientacion","Quiero orientación"],["A","Compra directa"],["B","Aportación a fideicomiso"],["C","Coinversión"]]}/>
 <Choice id="budget" label="Presupuesto en MXN (opcional)" value={budget} onChange={setBudget} options={apartment?[["por-definir","Por definir"],["menos-1","Menos de $1 millón"],["1-2","$1 a $2 millones"],["2-3","$2 a $3 millones"],["3-5","$3 a $5 millones"],["mas-5","Más de $5 millones"]]:[["por-definir","Por definir"],["menos-10","Menos de $10 millones"],["10-30","$10 a $30 millones"],["30-50","$30 a $50 millones"],["mas-50","Más de $50 millones"]]}/>
 <Choice id="timeline" label="Plazo de decisión (opcional)" value={timeline} onChange={setTimeline} options={[["explorando","Estoy explorando"],["0-3","En los próximos 3 meses"],["3-6","Entre 3 y 6 meses"],["6-12","Entre 6 y 12 meses"]]}/>
 <div className="field full"><label htmlFor="message">Tu consulta (opcional)</label><textarea id="message" name="message" maxLength={2000} rows={3} placeholder="Dudas, necesidades o disponibilidad para una visita…"/></div>
 </div></CollapsibleContent></Collapsible><div className="honeypot" aria-hidden="true"><label>Dejar vacío<input name="website" tabIndex={-1} autoComplete="off"/></label></div>
 <div className="consent"><Checkbox id="consent" checked={consent} onCheckedChange={v=>setConsent(v===true)}/><label htmlFor="consent">Autorizo el uso de mis datos para atender esta solicitud conforme a la <a href="/privacidad" target="_blank" rel="noreferrer">información de privacidad</a>. *</label></div>
 {error&&<p className="form-error" role="alert">{error}</p>}<button className="button gold submit-button" disabled={busy} type="submit">{busy?<>Guardando solicitud <LoaderCircle className="spin" size={18}/></>:<>Enviar mi solicitud <ArrowRight size={18}/></>}</button><p className="form-footnote"><LockKeyhole size={13}/> No envíes escrituras, identificaciones ni comprobantes bancarios en este formulario.</p></form>;
}
