"use client";
import { ArrowDown, ArrowUpRight, ArrowRight, Diamond, MapPin, Menu, X, ShieldCheck, LandPlot, FileText, Building2 } from "lucide-react";
import { useState } from "react";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

import { TechnicalDetails, LocationSection, Calculator, ProcessSection, BrandSection, FAQ, ContactSection, PropertyAssistant } from "./property-details";

export default function PropertySite() {
  const [menu, setMenu] = useState(false);
  return <>
    <a className="skip-link" href="#main">Ir al contenido</a>
    <header className="site-header"><a className="brand" href="#"><Diamond aria-hidden="true"/><span>DIAMOND<small>ASSET MANAGEMENT</small></span></a><nav className={menu ? "navigation open" : "navigation"} aria-label="Principal"><a onClick={()=>setMenu(false)} href="#terreno">El terreno</a><a onClick={()=>setMenu(false)} href="#ubicacion">Ubicación</a><a onClick={()=>setMenu(false)} href="#modalidades">Modalidades</a><a onClick={()=>setMenu(false)} href="#contacto">Contacto</a></nav><a className="header-cta" href="#contacto">Explorar la oportunidad <ArrowUpRight size={17}/></a><button className="menu-button" onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-label={menu?"Cerrar menú":"Abrir menú"}>{menu?<X/>:<Menu/>}</button></header>
    <main id="main">
    <section className="hero">
      <div className="hero-copy"><div className="eyebrow light">RESERVA TERRITORIAL · HIDALGO, MÉXICO</div><h1>El futuro necesita<br/>un <em>buen lugar.</em></h1><p>El Bindho. 7.6 hectáreas para estudiar tu próximo proyecto en el corredor San Agustín Tlaxiaca – Pachuca Poniente.</p><a className="button gold" href="#terreno">Descubrir el terreno <ArrowDown size={18}/></a><div className="hero-location"><MapPin size={16}/> San Agustín Tlaxiaca, Hidalgo</div></div>
      <div className="hero-art"><div className="property-label"><span>EL BINDHO</span><span>RESERVA 01 / REGIÓN CENTRO</span></div><div className="land-number">7.6<span>HECTÁREAS</span></div><div className="art-bottom"><span>Una escala distinta.<br/>Una visión de largo plazo.</span><Diamond size={40}/></div></div>
    </section>
    <div className="facts-bar"><div><span>SUPERFICIE NETA OFERTADA</span><strong>76,000 <small>m²</small></strong></div><div><span>PRECIO BASE / VENTA DIRECTA</span><strong>$399 <small>MXN/m²</small></strong></div><div><span>RÉGIMEN SEGÚN DOSSIER</span><strong>Propiedad privada</strong></div><a href="#modalidades">3 modalidades<br/>de operación <ArrowUpRight/></a></div>
    <section id="terreno" className="section intro"><div><div className="eyebrow">01 / EL ACTIVO</div><h2>Espacio para pensar<br/><em>en grande.</em></h2></div><div><p className="lead">Una reserva territorial de 76,000 m² con tres formas de estructurar una operación.</p><p>El Bindho se presenta para compradores, desarrolladores y socios operadores que buscan evaluar un proyecto en Hidalgo. Una conversación que empieza con datos claros y continúa con una revisión documental.</p><div className="feature-list"><span><LandPlot/> 7.6 hectáreas netas ofertadas</span><span><ShieldCheck/> Propiedad privada declarada en el dossier</span><span><FileText/> Expediente sujeto a revisión y confidencialidad</span></div></div></section>
    <LocationSection/><TechnicalDetails/>
    <section id="modalidades" className="section structures"><div className="eyebrow">02 / MODALIDADES DE OPERACIÓN</div><h2>Una propiedad.<br/><em>Tres formas de avanzar.</em></h2><Tabs defaultValue="A"><TabsList className="deal-tabs"><TabsTrigger value="A">01 · Compra directa</TabsTrigger><TabsTrigger value="B">02 · Fideicomiso</TabsTrigger><TabsTrigger value="C">03 · Coinversión</TabsTrigger></TabsList><TabsContent value="A"><div className="deal-panel"><div><Building2/><h3>Adquisición del activo</h3><p>Transmisión de la superficie neta ofertada bajo la modalidad “as-is / ad corpus”. La individualización del nuevo folio forma parte de las gestiones del adquirente, según el memorándum.</p></div><div className="deal-price"><span>PRECIO BASE TOTAL</span><strong>$30,324,000</strong><span>MXN · 76,000 m² × $399 MXN/m²</span><small>No incluye impuestos, gastos notariales, trámites ni urbanización.</small></div></div></TabsContent><TabsContent value="B"><div className="deal-panel"><div><Building2/><h3>Aportación a fideicomiso</h3><p>La propiedad aporta el terreno y el socio operador aporta el capital del proyecto. El dossier plantea anticipo a capital y participación del propietario sobre ventas brutas.</p></div><div className="deal-price"><span>PARTICIPACIÓN PLANTEADA DEL PROPIETARIO</span><strong>12–15%</strong><span>Sobre ventas brutas · Sujeto a negociación</span><small>No es una rentabilidad garantizada para el inversionista.</small></div></div></TabsContent><TabsContent value="C"><div className="deal-panel"><div><Building2/><h3>Coinversión para macrolotificación</h3><p>Esquema propuesto para subdivisión y urbanización de macrolotes, con fondeo del socio operador y distribución de utilidades sobre ventas.</p></div><div className="deal-price"><span>ESCALA CONCEPTUAL POR MACROLOTE</span><strong>~1 ha</strong><span>Según propuesta del dossier</span><small>Subdivisión, uso y urbanización sujetos a autorizaciones y factibilidad.</small></div></div></TabsContent></Tabs><Calculator/><a className="text-link" href="#contacto">Consultar una modalidad <ArrowUpRight size={17}/></a></section>
    <ProcessSection/><BrandSection/><FAQ/><ContactSection/>
    </main><footer><a className="brand" href="#"><Diamond/><span>DIAMOND<small>ASSET MANAGEMENT</small></span></a><p>Gestión de activos · Región Centro, México</p><div className="footer-links"><a href="/ficha">Ficha del activo</a><a href="/privacidad">Privacidad</a><a href="/gestion">Acceso de gestión</a></div><small>Información comercial basada en el memorándum aportado. Sujeta a validación documental, disponibilidad y acuerdo entre las partes.</small></footer><PropertyAssistant/>
  </>;
}
