"use client";
import { useEffect, useState } from "react";
import { ArrowUpRight, FileText, ArrowRight, MessageSquare, Download, MapPin, Check, ShieldCheck } from "lucide-react";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogTrigger } from "@/components/ui/dialog";
import { Table, TableBody, TableCell, TableRow } from "@/components/ui/table";
import { Slider } from "@/components/ui/slider";
import LeadForm, { type LeadRequest } from "./lead-form";
import PropertyLocation from "./property-location";
const money=(n:number)=>new Intl.NumberFormat("es-MX",{style:"currency",currency:"MXN",maximumFractionDigits:0}).format(n);
export const questions=[
 ["¿Cuál es el precio del terreno?","El memorándum indica $399 MXN por m² para compra directa. Para 76,000 m², el precio base es $30,324,000 MXN. No incluye impuestos, gastos notariales, trámites ni urbanización. Disponibilidad y condiciones requieren confirmación de la propiedad."],
 ["¿Es propiedad privada o ejidal?","El dossier lo describe como propiedad privada, no ejidal, y refiere un primer testimonio de escritura de la Notaría Pública No. 1 de Actopan. La titularidad, gravámenes y situación registral deben verificarse con la documentación y los profesionales correspondientes."],
 ["¿Dónde se encuentra exactamente?","El dossier sitúa El Bindho en el corredor San Agustín Tlaxiaca – Pachuca Poniente, Hidalgo. La ubicación exacta y los linderos se deben confirmar con el levantamiento y el archivo KMZ. Las fotografías de Hidalgo son solo contexto regional, no muestran el predio."],
 ["¿Se puede construir de inmediato?","No hay en la documentación recibida permisos, uso de suelo, factibilidades de servicios ni autorizaciones de subdivisión verificados. Cualquier desarrollo requiere confirmar esos elementos. Las posibilidades habitacionales o logísticas son propuestas de evaluación."],
 ["¿Por qué hay dos superficies distintas?","La superficie bruta declarada es de 76,758.90 m². Se ofertan 76,000 m² netos y se retienen 758.90 m² por la propiedad. La delimitación y la individualización registral deben revisarse antes de contratar."],
 ["¿Cómo recibo el expediente o solicito una visita?","Registra tu interés seleccionando documentación o visita. El equipo revisará la solicitud y coordinará los siguientes pasos. El dossier contempla acuerdo de confidencialidad y validación de contraparte para compartir documentación sensible. La solicitud no equivale a una cita confirmada ni a un NDA firmado."],
 ["¿El 12–15% es un rendimiento para mí?","No. En la modalidad de fideicomiso, el dossier plantea una participación del propietario del terreno sobre las ventas brutas, además de un anticipo a capital. La estructura final requiere negociación; no se anuncia rentabilidad garantizada."],
 ["¿Puedo adquirir solamente una hectárea?","La oferta recibida corresponde a los 76,000 m² netos. La propuesta de macrolotificación de aproximadamente una hectárea por lote es una estructura de coinversión por evaluar; no acredita que existan lotes individuales aprobados a la venta."]
];
export function TechnicalDetails(){return <section className="section technical"><div><div className="eyebrow">CARACTERÍSTICAS DEL ACTIVO</div><h2>Ficha de<br/><em>la propiedad.</em></h2><p className="section-description">La información de partida para tu análisis. Cifras y régimen declarados en el memorándum de inversión de El Bindho.</p><a className="text-link" href="/ficha"><FileText size={18}/> Ver ficha e imprimir <ArrowUpRight size={17}/></a></div><div className="spec-table"><Table><TableBody>{[["Denominación","El Bindho"],["Superficie bruta registral","76,758.90 m²"],["Superficie neta ofertada","76,000.00 m²"],["Fracción retenida por la propiedad","758.90 m²"],["Régimen declarado","Propiedad privada · No ejidal"],["Título referido","Primer testimonio de escritura"],["Notaría referida","No. 1 de Actopan, Hidalgo"],["Nuevo folio individualizado","Gestión contemplada en modalidad A"]].map(([k,v])=><TableRow key={k}><TableCell>{k}</TableCell><TableCell>{v}</TableCell></TableRow>)}</TableBody></Table><p className="caption">Datos aportados por la propiedad. La superficie exacta, el título y el folio deben corroborarse en la revisión documental.</p></div></section>}
export function LocationSection(){return <section id="ubicacion" className="location-section"><div className="location-map"><PropertyLocation property="el-bindho" caption="El Bindho está en el municipio de San Agustín Tlaxiaca, al poniente de Pachuca. El polígono exacto y el archivo KMZ se comparten con la documentación."/></div><div className="location-copy"><div className="eyebrow">HIDALGO / REGIÓN CENTRO</div><h2>Hidalgo.<br/><em>Pachuca Poniente.</em></h2><p>San Agustín Tlaxiaca – Pachuca Poniente es el corredor de referencia del terreno: un municipio vecino de Pachuca que forma parte de su zona metropolitana. Evalúa aquí el encaje de tu proyecto y solicita el polígono para estudiar su localización específica.</p><div className="location-points"><span><MapPin size={17}/> Municipio de San Agustín Tlaxiaca, Hidalgo</span><span><Check size={17}/> Polígono y KMZ con la documentación</span></div><a className="text-link" href="#solicitud">Solicitar el polígono <ArrowUpRight size={17}/></a></div></section>}
export function Calculator(){const [pct,setPct]=useState(30);const total=30324000;return <div className="calculator"><div><div className="eyebrow">PLANIFICACIÓN DE COMPRA DIRECTA</div><h3>Visualiza tu punto de partida.</h3><p>Explora un anticipo hipotético sobre el precio base. Su porcentaje y calendario se acuerdan entre las partes.</p></div><div><label className="range-label" htmlFor="deposit-slider">Anticipo ilustrativo <strong>{pct}%</strong></label><Slider id="deposit-slider" aria-label="Porcentaje de anticipo ilustrativo" min={10} max={100} step={5} value={[pct]} onValueChange={v=>setPct(v[0])}/><div className="calculator-results"><div><span>Anticipo</span><strong>{money(total*pct/100)}</strong></div><div><span>Saldo del precio</span><strong>{money(total*(1-pct/100))}</strong></div></div><p className="caption">Cifras en MXN. Simulación aritmética, no oferta de financiamiento. Gastos e impuestos no incluidos.</p></div></div>}
export function ProcessSection(){return <section id="proceso" className="section process"><div className="process-heading"><div><div className="eyebrow">03 — EL PROCESO</div><h2>Del primer contacto<br/><em>a la propuesta.</em></h2></div><p>La documentación, la viabilidad y los términos se revisan antes de formalizar una operación.</p></div><div className="process-grid">{[["01","Conocer tu proyecto","Registra tu interés y la modalidad que quieres evaluar."],["02","Revisar el expediente","Coordina la confidencialidad y la validación de contraparte antes de acceder a documentos sensibles."],["03","Validar en campo","Solicita una visita y revisa polígono, servicios, accesos y compatibilidad del proyecto."],["04","Estructurar el acuerdo","Presenta una carta de intención y define condiciones con tus asesores y la propiedad."]].map(([n,title,desc])=><article key={n}><span>{n}</span><h3>{title}</h3><p>{desc}</p></article>)}</div><div className="documents-note"><ShieldCheck/><div><strong>Documentación con el nivel de acceso adecuado.</strong><p>El dossier menciona levantamiento topográfico, archivo KMZ y testimonio testado. Su entrega debe confirmarse con el equipo. Esta página no contiene un expediente registral ni habilita descargas de documentos sensibles.</p></div><a href="#solicitud" className="text-link">Solicitar revisión <ArrowRight size={17}/></a></div></section>}
export function BrandSection(){return <section className="brand-section"><div className="eyebrow light">ASSET MANAGEMENT DIAMOND</div><h2>Visión patrimonial.<br/><em>Atención a cada decisión.</em></h2><p>Conectamos la información del activo con la conversación comercial: una presentación precisa, una evaluación ordenada y un canal directo para avanzar.</p><div className="brand-values"><span>Información clara</span><span>Trato directo</span><span>Confidencialidad documental</span></div></section>}
export function FAQ(){return <section id="preguntas" className="section faq"><div><div className="eyebrow">04 — PREGUNTAS FRECUENTES</div><h2>Antes de<br/><em>decidir.</em></h2><p>Respuestas basadas en el dossier recibido.</p></div><Accordion type="single" collapsible>{questions.map(([q,a],i)=><AccordionItem value={String(i)} key={q}><AccordionTrigger>{q}</AccordionTrigger><AccordionContent>{a}</AccordionContent></AccordionItem>)}</Accordion></section>}
export function ContactSection({request}:{request?:LeadRequest}){const [settings,setSettings]=useState<Record<string,string>>({});useEffect(()=>{fetch("/api/settings").then(r=>r.json() as Promise<Record<string,string>>).then(setSettings).catch(()=>{});},[]);return <section id="contacto" className="section contact-section"><div className="contact-copy"><div className="eyebrow light">05 — CONTACTO</div><h2>Hablemos<br/>de <em>El Bindho.</em></h2><p>Deja tus datos para explorar El Bindho con el equipo de Asset Management Diamond.</p><div className="contact-steps"><span><Check size={17}/> Registro inmediato de tu solicitud</span><span><Check size={17}/> Atención según tu interés y proyecto</span><span><Check size={17}/> Documentación por canal coordinado</span></div><div className="direct-contact">{settings.email&&<a href={"mailto:"+settings.email}>{settings.email} <ArrowUpRight size={16}/></a>}{settings.whatsapp&&<a href={"https://wa.me/"+settings.whatsapp+"?text="+encodeURIComponent("Hola, me interesa El Bindho y quisiera recibir información.")} target="_blank" rel="noreferrer">Conversar por WhatsApp <ArrowUpRight size={16}/></a>}{settings.bookingUrl&&<a href={settings.bookingUrl} target="_blank" rel="noreferrer">Consultar agenda de reuniones <ArrowUpRight size={16}/></a>}</div><span className="contact-ref">EL BINDHO · 76,000 M² · HIDALGO</span></div><LeadForm request={request}/></section>}
export function PropertyAssistant(){const [answer,setAnswer]=useState(-1);return <Dialog><DialogTrigger asChild><button className="assistant-button" aria-label="Abrir asistente de preguntas sobre El Bindho"><MessageSquare size={19}/><span>Resuelve tus dudas</span></button></DialogTrigger><DialogContent className="assistant-dialog"><DialogHeader><div className="eyebrow">DIAMOND / ASISTENTE DEL ACTIVO</div><DialogTitle>¿Qué te gustaría conocer?</DialogTitle><DialogDescription>Respuestas automáticas basadas en el memorándum. Selecciona una pregunta.</DialogDescription></DialogHeader><div className="assistant-options">{questions.slice(0,6).map(([q],i)=><button key={q} onClick={()=>setAnswer(i)} aria-pressed={answer===i}>{q}<ArrowRight size={15}/></button>)}</div>{answer>=0&&<div className="assistant-answer" aria-live="polite">{questions[answer][1]}</div>}<a href="#solicitud" className="text-link" onClick={()=>{document.querySelector<HTMLButtonElement>('[data-slot="dialog-close"]')?.click();}}>Hablar sobre mi proyecto <ArrowUpRight size={17}/></a></DialogContent></Dialog>}
