"use client";
import { useState } from "react";
import { ArrowLeft, ArrowUpRight, ArrowDown, MapPin, Check } from "lucide-react";
import { AgencyHeader, AgencyFooter } from "@/app/agency-shell";
import LeadForm from "@/app/lead-form";
import PropertyLocation from "@/app/property-location";
import ShareBar from "@/app/share-bar";
import WhatsAppContact from "@/app/whatsapp-contact";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { ubicaciones } from "@/lib/ubicaciones";
const tecKm=ubicaciones["villas-de-la-hacienda"].referencias[0].km.toLocaleString("es-MX",{minimumFractionDigits:1});
const questions=[
 ["¿Cuál es el precio de venta?","Te lo compartimos junto con las condiciones de venta en cuanto nos escribas. Registra tu interés o escríbenos y te respondemos con la ficha completa."],
 ["¿Cuántos metros, recámaras y baños tiene?","La superficie, la distribución y los estacionamientos vienen en la ficha completa. Solicítala y te la enviamos para que la compares con calma antes de visitarlo."],
 ["¿Hay elevador?","El departamento está en el nivel 3B, un nivel alto del Edificio 3. Si el acceso es importante para ti, cuéntanoslo y lo revisamos contigo antes del recorrido."],
 ["¿Se puede comprar con crédito?","Sí, puedes comprarlo de contado o con crédito bancario o Infonavit, sujeto a la aprobación de la institución y al avalúo. Indícalo en tu solicitud y te orientamos sobre el siguiente paso."],
 ["¿Qué documentación puedo revisar?","Antes de cualquier firma te compartimos la documentación del inmueble por un canal privado, para que tú, tu notario o tu banco la revisen con tiempo."],
 ["¿Cómo agendo una visita?","Solicítala en el formulario o por WhatsApp y comparte tu disponibilidad. Coordinamos contigo el día y la hora del recorrido."]
];
const facts:[string,string][]=[["Tipo de inmueble","Departamento"],["Operación","Venta"],["Dirección","Boulevard S.O.P. No. 3"],["Edificio / nivel","3 / 3B, nivel alto"],["Colonia","Fraccionamiento Villas de la Hacienda"],["Municipio / C.P.","Atizapán de Zaragoza / 52929"],["Forma de compra","Contado, o crédito bancario o Infonavit sujeto a aprobación"],["Medidas y distribución","En la ficha completa: solicítala"]];
export default function Apartment(){const [request,setRequest]=useState({intent:"informacion",modality:"orientacion",placement:"departamento"});function inquire(intent:string){setRequest({intent,modality:"orientacion",placement:"departamento-"+intent});}
return <div className="agency-site apartment-site"><a className="skip-link" href="#main">Ir al contenido</a><AgencyHeader/><main id="main">
<div className="apartment-breadcrumb"><a href="/#propiedades"><ArrowLeft size={16}/> Todas las propiedades</a><span>DMD–002 / DEPARTAMENTO EN VENTA</span></div>
<section className="apartment-hero"><div><p className="agency-kicker">ATIZAPÁN DE ZARAGOZA · ESTADO DE MÉXICO</p><h1>Villas de<br/><em>la Hacienda.</em></h1><p className="apartment-intro">Deja de rentar. Empieza tu<br/>patrimonio en Atizapán.</p><div className="apartment-address"><MapPin size={18}/><span>Boulevard S.O.P., Fraccionamiento Villas de la Hacienda<br/>A {tecKm} km por calle del Tec de Monterrey, Campus Estado de México</span></div><div className="hero-jumps"><a href="#ubicacion" className="agency-action">Ver la ubicación <ArrowDown size={18}/></a><a href="#ficha" className="agency-action">Conocer la propiedad <ArrowDown size={18}/></a></div></div><aside className="apartment-interest"><p className="agency-kicker">VENTA · DMD–002</p><h2>Hablemos de<br/>tu próximo hogar.</h2><dl><div><dt>Precio de venta</dt><dd>A consultar</dd></div><div><dt>Nivel</dt><dd>3B · nivel alto</dd></div><div><dt>Tec de Monterrey CEM</dt><dd>{tecKm} km por calle</dd></div></dl><a href="#contacto" className="button gold" onClick={()=>inquire("visita")}>Agenda tu visita <ArrowUpRight size={18}/></a><a href="#contacto" className="agency-action" onClick={()=>inquire("informacion")}>Recibe la ficha completa <ArrowUpRight size={17}/></a><WhatsAppContact property="villas-de-la-hacienda"/><ShareBar property="villas-de-la-hacienda" tone="dark" label="Comparte este departamento"/></aside></section>
<section id="ficha" className="apartment-facts"><div><p className="agency-kicker">LA PROPIEDAD</p><h2>Tu siguiente paso<br/><em>puede estar aquí.</em></h2><p>Un departamento en el nivel 3B del Edificio 3, dentro de Villas de la Hacienda: una colonia habitacional ya consolidada, con la privacidad de un piso alto. Es para quien quiere dejar de pagar renta y empezar un patrimonio propio en el norte del Valle de México, y para quien busca un departamento para rentar.</p></div><dl>{facts.map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></section>
<section id="ubicacion" className="apartment-location"><div><p className="agency-kicker">UBICACIÓN</p><h2>Tu vida cotidiana.<br/><em>A pocos kilómetros.</em></h2><p>Mira el departamento en el mapa, calcula tu ruta y revisa la distancia por calle a los lugares de referencia de la zona.</p></div><PropertyLocation property="villas-de-la-hacienda" caption="Boulevard S.O.P., Fraccionamiento Villas de la Hacienda, C.P. 52929, Atizapán de Zaragoza, Estado de México. Te indicamos el acceso exacto al coordinar tu visita."/></section>
<section className="apartment-faq"><div><p className="agency-kicker">ANTES DE AVANZAR</p><h2>Las preguntas<br/><em>importan.</em></h2><p>Lo que más nos preguntan sobre este departamento.</p></div><Accordion type="single" collapsible>{questions.map(([q,a],i)=><AccordionItem value={String(i)} key={q}><AccordionTrigger>{q}</AccordionTrigger><AccordionContent>{a}</AccordionContent></AccordionItem>)}</Accordion></section>
<section className="apartment-contact" id="contacto"><div><p className="agency-kicker">HABLEMOS DE VILLAS DE LA HACIENDA</p><h2>El primer paso<br/>es <em>conversar.</em></h2><p>Cuéntanos qué necesitas conocer del departamento. Tu solicitud quedará registrada con una referencia para darle seguimiento.</p><ul><li><Check size={17}/> Ficha completa y precio por mensaje</li><li><Check size={17}/> Documentación por un canal privado</li><li><Check size={17}/> Recorrido en el día y la hora que acordemos</li></ul><span className="apartment-contact-ref">DMD–002 · ATIZAPÁN DE ZARAGOZA</span></div><LeadForm propertyId="villas-de-la-hacienda" request={request}/></section>
<div className="apartment-other"><span>También en el portafolio Diamond</span><a href="/propiedades/el-bindho">El Bindho · 7.6 hectáreas en Hidalgo <ArrowUpRight size={20}/></a></div>
</main><AgencyFooter/></div>;}
